config/routes.rb
Rails.application.routes.draw do
  root "movies#index"
  
  # nested resource enforces parent-child relationship
  resources :movies do
    resources :reviews
  end

  resources :users
  get "signup", to: "users#new"

  resource :session, only: [:new, :create, :destroy]
  get "signin", to: "sessions#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :reviews, dependent: :destroy

    validates :title, :released_on, :duration, presence: true
    validates :description, length: { minimum: 25 }
    validates :total_gross, numericality: { greater_than_or_equal_to: 0 }
    validates :image_file_name, format: {
        with: /\w+\.(jpg|png)\z/i,
        message: "must be a JPG or PNG image"
    }

    RATINGS = %w(G PG PG-13 PG-15 R NC-17)
    validates :rating, inclusion: { in: RATINGS,
        message: "%{value} is not a valid rating"
    }
    

    def self.prev_released
        where("released_on < ?", Time.now).order("released_on desc")
    end
    
    def flop?
        if (reviews.count < 50 && average_stars < 4)
            (total_gross.blank? || total_gross < 200000000)
        end
    end

    def average_stars
        reviews.average(:stars).to_i || 0
    end

    def average_stars_as_percent
        (average_stars / 5.0 ) * 100.0
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie

  validates :name, presence: true
  validates :comment, length: { minimum: 4 }
  
  STARS = [1, 2, 3, 4, 5]

  validates :stars, inclusion: { 
    in: STARS, 
    message: "Ratings must be between 1 star and 5 stars" 
  }

  def stars_as_percent
    (stars / 5.0 ) * 100.0
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true

  validates :email, format: { with: /\S+@\S+/ },
    uniqueness: { case_sensitive: false }

  validates :password, length: { minimum: 10, allow_blank: true }

  validates :username, presence: true, 
    uniqueness: { case_sensitive: false },
    format: { with: /[a-z0-9]/i }

  # access user gravatar profile image
  def gravatar_id
    Digest::MD5::hexdigest(email.downcase)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

    def index
        @movies = Movie.all
    end

    def show
        @movie = find_movie
        @review = @movie.reviews.new
    end

    def edit
        @movie = find_movie
    end

    def update
        @movie = find_movie
        if @movie.update(event_param)
            # redirect to show view and displays message for user
            redirect_to movie_path(@movie), notice: "Movie successfully updated!"
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def new
        @movie = Movie.new
    end

    def create
        @movie = Movie.new(event_param)
        if @movie.save
            redirect_to movie_path(@movie), notice: "Movie successfully created!"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def destroy
        find_movie.destroy
        redirect_to movies_path, alert: "Movie successfully deleted!"
    end

    private

    # specifies attributes we want to permit for update
    def event_param
        params.require(:movie).permit(:title, :description, :rating, :released_on, :total_gross, :director, :image_file_name, :duration);
    end

    def find_movie
        Movie.find(params[:id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_movie

    def index
        @reviews = @movie.reviews.order(created_at: :desc)
    end

    def new
        @review = @movie.reviews.new
    end

    def create
        @review = @movie.reviews.new(reviews_params)
        if @review.save
            redirect_to movie_reviews_path(@movie), notice: "You've successfully added a review!"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @review = @movie.reviews.find(params[:id])
    end

    def update
        @review = @movie.reviews.find(params[:id])
        if @review.update(reviews_params)
            redirect_to movie_reviews_path(@movie), notice: "You've successfully edited your review!"
        else
            render :edit, status: :unprocessable_entity
        end
    end


    def destroy
        @movie.reviews.find(params[:id]).destroy

        redirect_to movie_path(@movie), alert: "Review successfully deleted!"
    end

    private

    def reviews_params
        params.require(:review).permit(:name, :comment, :stars);
    end

    def set_movie
        # grabs the associated movie
        @movie = Movie.find(params[:movie_id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # find user and authenticate
    user = User.find_by(email: params[:email_or_username]) || User.find_by(username: params[:email_or_username])
    
    if user && user.authenticate(params[:password])
      # store user ID in hash
      session[:user_id] = user.id
      redirect_to user, notice: "Welcome back #{user.username}!"
    else
      flash.now[:alert] = "Incorrect email/password combination!"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to movies_path, status: :see_other, notice: "You have signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            # logs the user in
            session[:user_id] = @user.id
            redirect_to user_path(@user), notice: "Thanks for signing up!"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def show
        @user = find_user
    end

    def edit
        @user = find_user
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            # redirect to show view and displays message for user
            redirect_to user_path(@user), notice: "Profile successfully updated!"
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        find_user.destroy
        session[:user_id] = nil
        redirect_to movies_path, status: :see_other, alert: "Profile successfully deleted!"
    end

    private

    def user_params
        params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end

    def find_user
        User.find(params[:id])
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
    # current_user is used globally
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
    def total_gross(movie)
        movie.flop? ? "Flop" : number_to_currency(movie.total_gross, precision: 0)
    end

    def year_of(movie)
        # formats date to year
        movie.released_on.year
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
    def average_reviews_helper(movie)
        if movie.average_stars.zero?
            content_tag(:strong, "No reviews")
        else
            pluralize(movie.average_stars, "star")
        end
    end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def profile_image(user)
        url = "http://secure.gravatar.com/avatar/#{user.gravatar_id}"
        image_tag(url, alt: user.name)
    end
end

app/views/layouts/_flash.html.erb
 <% if flash[:notice] %>
    <div class="flash notice">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="flash alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <p>
        Copyright © <%= Time.now.year %>
        <%= link_to "All Flix No Chill", "https://nomads-test-store.netlify.app/"%>
    </p>
</footer>

app/views/layouts/_header.html.erb
 <header>
    <nav>
      <%# <img src="app/assets/images/logo.png" alt="Flix logo"> %>
      <%= link_to image_tag("all_flix_logo.png"), root_path %>
      <ul class="left">
        <li><%= link_to "All movies", movies_path %></li>
      </ul>
      <ul class="right">
        <% if current_user %>
          <%= link_to current_user.username, current_user %>
          <li><%= link_to "Account settings", edit_user_path(current_user), class: "button" %></li>
          <li><%= link_to "Sign out", session_path, data: {turbo_method: :delete, turbo_confirm: "Sign out?"}, class: "button" %></li>
        <% else %>
          <li><%= link_to "Sign in", signin_path, class: "button" %></li>
          <li><%= link_to "Sign up", signup_path, class: "button" %></li>
        <% end %>
      </ul>
    </nav>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>All Flix No Chill</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "layouts/header" %>

    <div class="content">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>

  </body>
</html>

app/views/movies/_movie_form.html.erb
<%= form_with(model: movie) do |f| %>
    <%= render "shared/errors", object: movie %>

    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true %>

    <%= f.label :description %>
    <%= f.text_area :description, rows: 5 %>
   
    <%= f.label :rating %>
    <%= f.select :rating, Movie::RATINGS, prompt: "Pick one" %>

    <%= f.label :director %>
    <%= f.text_field :director %>

    <%= f.label :duration %>
    <%= f.text_field :duration %>

    <%= f.label :release_date %>
    <%= f.date_field :released_on %>
 
    <%= f.label :box_office %>
    <%= f.number_field :total_gross %>

    <%= f.label :image_file_name %>
    <%= f.text_field :image_file_name %>

    <%= f.submit %>
<% end %>

app/views/movies/edit.html.erb
<h2>Edit <%= @movie.title %> </h2>

<%= render "movie_form", movie: @movie %>

app/views/movies/index.html.erb
<% @movies.each do |movie| %>
    <section class="movie">
        <div class="image">
            <%= link_to image_tag(movie.image_file_name), movie_path(movie) %>
        </div>
        <div class="summary">
            <h2><%= link_to movie.title, movie_path(movie) %></h2>
            <p>
                Synopsis: <i><%= truncate(movie.description, length: 35, separator: " ")  %></i>
            </p>
            <h3>
                Director: <%= movie.director %>
            </h3>
            <h3>
                Duration: <%= movie.duration %>
            </h3>
            <h3>
                Box Office: <%= total_gross(movie) %>
            </h3>
            <h3>
                Released on: <%= movie.released_on %>
            </h3>
            <%= render "shared/stars", percent: movie.average_stars_as_percent %>
        </div>
    </section>
<% end %>
<section class="admin">
    <%= link_to "Add new movie", new_movie_path, class: "button" %>
</section>

app/views/movies/new.html.erb
<h2>Add a New Movie</h2>

<%= render "movie_form", movie: @movie %>

app/views/movies/show.html.erb
<section class="movie-details">
    <div class="image">
        <%= image_tag @movie.image_file_name %>
    </div>
    <div class="summary-details">
        <h2><%= @movie.title %></h2>
        <p>
            Synopsis: <i><%= @movie.description  %></i>
        </p>
        <h3>
            Director: <%= @movie.director %>
        </h3>
        <h3>
            Duration: <%= @movie.duration %>
        </h3>
        <h3>
            Rating: <%= @movie.rating %>
        </h3>
        <h3>
            Release year: <%= year_of(@movie) %>
        </h3>
        <h3>
            Box Office: <%= total_gross(@movie) %>
        </h3>

        <% if @movie.reviews %>
            <div class="reviews">
                <%= link_to pluralize(@movie.reviews.count, "review"), movie_reviews_path(@movie) %>
            </div>
        <% end %>

        <%= link_to "Add review", new_movie_review_path(@movie), class: "review"%>
    </div>
</section>

<section class="admin">
    <%= link_to "Edit movie", edit_movie_path(@movie), class: "button" %>
    <%# override method with turbo_method to delete resource %>
    <%= link_to "Delete movie", movie_path(@movie), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "button" %>
</section>

app/views/reviews/_review_form.html.erb
<%# All models from nested resources need to be passed as an array arg %>
<%= form_with(model: [@movie, @review]) do |f| %>
     <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, maxlength: 15, size: 5 %>

    <%= f.label :stars %>
        <% Review::STARS.each do |star| %>
            <span class="star">
                <%= f.radio_button :stars, star %>
                <%= label_tag star %>
            </span>
        <% end %>

    <%= f.label :comment %>
    <%= f.text_area :comment, autofocus: true, maxlength: 100 %>

    <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<h2>Edit review for: <%= link_to @movie.title, movie_reviews_path(@movie) %></h2>

<%= render "shared/errors", object: @review %>

<%= render "review_form", review: @review %>

app/views/reviews/index.html.erb
<h2>Reviews for <%= link_to @movie.title, movie_path(@movie) %></h2>
<% if @reviews.count > 0 %>
    <ul class="reviews">
        <% @reviews.each do |review| %>
            <li>
                <%= render "shared/stars", percent: review.stars_as_percent %> 
                <p>
                    <%= review.name %>
                    <span class="date">
                        Review created <%= time_ago_in_words(review.created_at) %> ago
                    </span>
                </p>
                <p>
                    <i><%= review.comment %></i>
                </p>
                <%= link_to "Edit review", edit_movie_review_path(review.movie, review), class: "button" %>
                <%# movie_review_path requires two args for the associated movie id and the review id %>
                <%= link_to "Delete review", movie_review_path(review.movie, review), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete review?"}, class: "button" %>
            </li>
        <% end %>
    </ul>
<% else %>
    <p>Oh no! There are no reviews yet for this movie. Please check again later...</p>
<% end %>

<%= link_to "Go back to #{@movie.title}", movie_path(@movie) %>

app/views/reviews/new.html.erb
<h2>Add review for <%= link_to @movie.title, movie_path(@movie) %></h2>
<%= render "shared/errors", object: @review %>

<%= render "review_form", review: @review %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <section class="errors">
        <h2>
            Yikes! Your form could not be saved.
        </h2>
        <h3>
            Please correct the following
            <%= pluralize(object.errors.size, "error") %>
        </h3>
        <ul>
            <% object.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </section>
<% end %>

app/views/shared/_stars.html.erb
<div class="star-rating">
  <div class="back-stars">
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <div class="front-stars" style="width: <%= percent %>%">
      <span>★</span>
      <span>★</span>
      <span>★</span>
      <span>★</span>
      <span>★</span>
    </div>
  </div>
</div>

app/views/users/_user_form.html.erb
<%= form_with(model: user) do |f| %>
<%= render "shared/errors", object: user %>

    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>

    <%= f.label :username %>
    <%= f.text_field :username, placeholder: "Alphanumerical characters only!" %>

    <%= f.label :email %>
    <%= f.email_field :email%>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %>

    <% if user.new_record? %>
        <%= f.submit "Create profile" %>
    <% else %>
        <%= f.submit "Update profile" %>
    <% end %>
<% end %>

app/views/users/edit.html.erb
<h2>Edit user profile</h2>
<%= render "user_form", user: @user %>

app/views/users/index.html.erb
<h2>Users</h2>
<ul>
    <% @users.each do |user| %>
        <li>
            <%= link_to user.name, user_path(user) %>
            <%= user.email %>
        </li>
    <% end %>
</ul>

app/views/users/new.html.erb
<h2>Create user profile</h2>
<%= render "shared/errors", object: @user %>
<%= render "user_form", user: @user %>

app/views/users/show.html.erb
<h2>User profile</h2>
<section class="user">
    <%= profile_image(@user) %>
    <p><%= @user.username %></p>
    <p><%= mail_to(@user.email) %></p>
    <p><i>Member since: <%= @user.created_at.strftime("%b %Y") %></i></p>

    <div class="actions">
        <%= link_to "Edit profile", edit_user_path(@user), class: "button edit" %>
        <%= link_to "Delete profile", user_path(@user), data: { 
            turbo_method: :delete, turbo_confirm: "Are you sure you want to delete your profile?"
        }, class: "button delete" %>
    </div>
</section>